### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by heyaibek** [luontola/cqrs-hotel#2]
Hi, @luontola

Unfortunately I've got error while starting the project with following commands `docker-compose pull` and `docker-compose up -d`:

`ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.`

How can you resolve it?

Best regards,
@aimkata

**Comment by aimkata** [comment]
Solved by re-installing my `docker-compose` (See ref. [https://docs.docker.com/compose/install/#install-compose](https://docs.docker.com/compose/install/#install-compose))
